const actions = {
  FETCH_MOVIE_LIST: 'FETCH_MOVIE_LIST',
  SET_MOVIE_LIST: 'SET_MOVIE_LIST',
  SET_DISPLAYED_MOVIE_LIST: 'SET_DISPLAYED_MOVIE_LIST',
  SET_ARE_MOVIE_LISTS_MATCHING: 'SET_ARE_MOVIE_LISTS_MATCHING'
};

export default actions;
